name: aliment
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Dependencies
  flutter_native_splash: ^2.4.4
  go_router: ^14.2.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  intl: ^0.20.2
  image_picker: ^1.0.4
  firebase_storage: ^12.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Konfigurasi Splash Screen
# flutter_native_splash:
#   color: "#FFFFFF"
#   image: "assets/images/logo_aliment.png"
#   android: true
#   ios: true
#   web: true

flutter:
  uses-material-design: true

  fonts:
    - family: Gabarito
      fonts:
        - asset: assets/fonts/Gabarito-VariableFont_wght.ttf

  assets:
    - assets/images/logo_aliment.png
    - assets/images/get_started_img.png
    - assets/icons/back_button.png
    - assets/icons/Google_logo.png
    - assets/icons/user_profile.png